//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  page: Page;
  pageConnection: PageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  page?: InputMaybe<PageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | Page | Folder;

export type HomeNews = {
  __typename?: 'HomeNews';
  item?: Maybe<Scalars['String']['output']>;
};

export type HomeSpecialization = {
  __typename?: 'HomeSpecialization';
  item?: Maybe<Scalars['String']['output']>;
};

export type HomeEducation = {
  __typename?: 'HomeEducation';
  item?: Maybe<Scalars['String']['output']>;
};

export type HomeExperience = {
  __typename?: 'HomeExperience';
  item?: Maybe<Scalars['String']['output']>;
};

export type HomeAdminExperience = {
  __typename?: 'HomeAdminExperience';
  item?: Maybe<Scalars['String']['output']>;
};

export type HomePublicationSummary = {
  __typename?: 'HomePublicationSummary';
  item?: Maybe<Scalars['String']['output']>;
};

export type HomePatents = {
  __typename?: 'HomePatents';
  item?: Maybe<Scalars['String']['output']>;
};

export type HomeSupervision = {
  __typename?: 'HomeSupervision';
  item?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  title: Scalars['String']['output'];
  name: Scalars['String']['output'];
  role: Scalars['String']['output'];
  affiliation?: Maybe<Scalars['String']['output']>;
  email1?: Maybe<Scalars['String']['output']>;
  email2?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  orcid?: Maybe<Scalars['String']['output']>;
  scholar?: Maybe<Scalars['String']['output']>;
  photo?: Maybe<Scalars['String']['output']>;
  news?: Maybe<Array<Maybe<HomeNews>>>;
  specialization?: Maybe<Array<Maybe<HomeSpecialization>>>;
  education?: Maybe<Array<Maybe<HomeEducation>>>;
  experience?: Maybe<Array<Maybe<HomeExperience>>>;
  adminExperience?: Maybe<Array<Maybe<HomeAdminExperience>>>;
  publicationSummary?: Maybe<Array<Maybe<HomePublicationSummary>>>;
  patents?: Maybe<Array<Maybe<HomePatents>>>;
  supervision?: Maybe<Array<Maybe<HomeSupervision>>>;
  body?: Maybe<Scalars['RichText']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeNewsFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomeSpecializationFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomeEducationFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomeExperienceFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomeAdminExperienceFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomePublicationSummaryFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomePatentsFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomeSupervisionFilter = {
  item?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HomeFilter = {
  title?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  affiliation?: InputMaybe<StringFilter>;
  email1?: InputMaybe<StringFilter>;
  email2?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  orcid?: InputMaybe<StringFilter>;
  scholar?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
  news?: InputMaybe<HomeNewsFilter>;
  specialization?: InputMaybe<HomeSpecializationFilter>;
  education?: InputMaybe<HomeEducationFilter>;
  experience?: InputMaybe<HomeExperienceFilter>;
  adminExperience?: InputMaybe<HomeAdminExperienceFilter>;
  publicationSummary?: InputMaybe<HomePublicationSummaryFilter>;
  patents?: InputMaybe<HomePatentsFilter>;
  supervision?: InputMaybe<HomeSupervisionFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type Page = Node & Document & {
  __typename?: 'Page';
  title: Scalars['String']['output'];
  body?: Maybe<Scalars['RichText']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updatePage: Page;
  createPage: Page;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  page?: InputMaybe<PageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  page?: InputMaybe<PageMutation>;
};

export type HomeNewsMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomeSpecializationMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomeEducationMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomeExperienceMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomeAdminExperienceMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomePublicationSummaryMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomePatentsMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomeSupervisionMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  affiliation?: InputMaybe<Scalars['String']['input']>;
  email1?: InputMaybe<Scalars['String']['input']>;
  email2?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  orcid?: InputMaybe<Scalars['String']['input']>;
  scholar?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  news?: InputMaybe<Array<InputMaybe<HomeNewsMutation>>>;
  specialization?: InputMaybe<Array<InputMaybe<HomeSpecializationMutation>>>;
  education?: InputMaybe<Array<InputMaybe<HomeEducationMutation>>>;
  experience?: InputMaybe<Array<InputMaybe<HomeExperienceMutation>>>;
  adminExperience?: InputMaybe<Array<InputMaybe<HomeAdminExperienceMutation>>>;
  publicationSummary?: InputMaybe<Array<InputMaybe<HomePublicationSummaryMutation>>>;
  patents?: InputMaybe<Array<InputMaybe<HomePatentsMutation>>>;
  supervision?: InputMaybe<Array<InputMaybe<HomeSupervisionMutation>>>;
  body?: InputMaybe<Scalars['RichText']['input']>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['RichText']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type HomeNewsFilter = {
  item?: StringFilter | null | undefined;
};

export type HomeSpecializationFilter = {
  item?: StringFilter | null | undefined;
};

export type HomeEducationFilter = {
  item?: StringFilter | null | undefined;
};

export type HomeExperienceFilter = {
  item?: StringFilter | null | undefined;
};

export type HomeAdminExperienceFilter = {
  item?: StringFilter | null | undefined;
};

export type HomePublicationSummaryFilter = {
  item?: StringFilter | null | undefined;
};

export type HomePatentsFilter = {
  item?: StringFilter | null | undefined;
};

export type HomeSupervisionFilter = {
  item?: StringFilter | null | undefined;
};

export type RichTextFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
};

export type HomeFilter = {
  title?: StringFilter | null | undefined;
  name?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  affiliation?: StringFilter | null | undefined;
  email1?: StringFilter | null | undefined;
  email2?: StringFilter | null | undefined;
  phone?: StringFilter | null | undefined;
  orcid?: StringFilter | null | undefined;
  scholar?: StringFilter | null | undefined;
  photo?: ImageFilter | null | undefined;
  news?: HomeNewsFilter | null | undefined;
  specialization?: HomeSpecializationFilter | null | undefined;
  education?: HomeEducationFilter | null | undefined;
  experience?: HomeExperienceFilter | null | undefined;
  adminExperience?: HomeAdminExperienceFilter | null | undefined;
  publicationSummary?: HomePublicationSummaryFilter | null | undefined;
  patents?: HomePatentsFilter | null | undefined;
  supervision?: HomeSupervisionFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type PageFilter = {
  title?: StringFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type HomePartsFragment = { __typename: 'Home', title: string, name: string, role: string, affiliation: string | null, email1: string | null, email2: string | null, phone: string | null, orcid: string | null, scholar: string | null, photo: string | null, body: TinaMarkdownContent | null, news: Array<{ __typename: 'HomeNews', item: string | null } | null> | null, specialization: Array<{ __typename: 'HomeSpecialization', item: string | null } | null> | null, education: Array<{ __typename: 'HomeEducation', item: string | null } | null> | null, experience: Array<{ __typename: 'HomeExperience', item: string | null } | null> | null, adminExperience: Array<{ __typename: 'HomeAdminExperience', item: string | null } | null> | null, publicationSummary: Array<{ __typename: 'HomePublicationSummary', item: string | null } | null> | null, patents: Array<{ __typename: 'HomePatents', item: string | null } | null> | null, supervision: Array<{ __typename: 'HomeSupervision', item: string | null } | null> | null };

export type PagePartsFragment = { __typename: 'Page', title: string, body: TinaMarkdownContent | null };

export type HomeQueryVariables = Exact<{
  relativePath: string;
}>;


export type HomeQuery = { home: { __typename: 'Home', id: string, title: string, name: string, role: string, affiliation: string | null, email1: string | null, email2: string | null, phone: string | null, orcid: string | null, scholar: string | null, photo: string | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, news: Array<{ __typename: 'HomeNews', item: string | null } | null> | null, specialization: Array<{ __typename: 'HomeSpecialization', item: string | null } | null> | null, education: Array<{ __typename: 'HomeEducation', item: string | null } | null> | null, experience: Array<{ __typename: 'HomeExperience', item: string | null } | null> | null, adminExperience: Array<{ __typename: 'HomeAdminExperience', item: string | null } | null> | null, publicationSummary: Array<{ __typename: 'HomePublicationSummary', item: string | null } | null> | null, patents: Array<{ __typename: 'HomePatents', item: string | null } | null> | null, supervision: Array<{ __typename: 'HomeSupervision', item: string | null } | null> | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: HomeFilter | null | undefined;
}>;


export type HomeConnectionQuery = { homeConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Home', id: string, title: string, name: string, role: string, affiliation: string | null, email1: string | null, email2: string | null, phone: string | null, orcid: string | null, scholar: string | null, photo: string | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, news: Array<{ __typename: 'HomeNews', item: string | null } | null> | null, specialization: Array<{ __typename: 'HomeSpecialization', item: string | null } | null> | null, education: Array<{ __typename: 'HomeEducation', item: string | null } | null> | null, experience: Array<{ __typename: 'HomeExperience', item: string | null } | null> | null, adminExperience: Array<{ __typename: 'HomeAdminExperience', item: string | null } | null> | null, publicationSummary: Array<{ __typename: 'HomePublicationSummary', item: string | null } | null> | null, patents: Array<{ __typename: 'HomePatents', item: string | null } | null> | null, supervision: Array<{ __typename: 'HomeSupervision', item: string | null } | null> | null } | null } | null> | null } };

export type PageQueryVariables = Exact<{
  relativePath: string;
}>;


export type PageQuery = { page: { __typename: 'Page', id: string, title: string, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PageConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PageFilter | null | undefined;
}>;


export type PageConnectionQuery = { pageConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Page', id: string, title: string, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  title
  name
  role
  affiliation
  email1
  email2
  phone
  orcid
  scholar
  photo
  news {
    __typename
    item
  }
  specialization {
    __typename
    item
  }
  education {
    __typename
    item
  }
  experience {
    __typename
    item
  }
  adminExperience {
    __typename
    item
  }
  publicationSummary {
    __typename
    item
  }
  patents {
    __typename
    item
  }
  supervision {
    __typename
    item
  }
  body
}
    `;
export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  body
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  